### ISSUE TITLE
CombatToNormal dialogue is used instead of LostToNormal in some situations

### ISSUE THREAD

**Issue by Vermunds** [powerof3/po3-Tweaks#1]
While your fix does fix the problem where LostToNormal is used instead of CombatToNormal, it also causes CombatToNormal to be used when it shouldn't.
Example: Hit an NPC, and hide nearby. When it stops searching it will say things like "That's the last of them", which is not the correct behavior. This is when dialogues like "Must have scared them off" should be used.

For reference, I also attempted to fix this a while ago, and this is what I came up with. It's not perfect either, it assumes that the combat can only end with CombatToNormal if one of the participants is dead, which may not always be the case.
https://github.com/Vermunds/EngineFixesSkyrim64/commit/da25ead00272885b7891c26c904a982b2628ab69

**Comment by powerof3** [comment]
Thanks for letting me know, I wasn't aware I reversed the bug. 

 I found where the game actually calls `CombatToNormal` dialogue at `1404FE1C5`.

![image](https://user-images.githubusercontent.com/32599957/122182521-f928e800-cea7-11eb-9c76-4781b67a9536.png)

It does assume the target is dead so your fix was on point, but somehow this doesn't get called (? haven't verified that) and it might be better to fix the underlying cause altogether.

**Comment by Vermunds** [comment]
Nice find.
I don't have `CombatController` decoded so the code is not too meaningful for me, but the function you found appears to be called. Yet, for some reason it doesn't seem to have any effect.
I even removed the call that triggers `LostToNormal`, in case it somehow overrode it, but it just results in no dialogue at all.

So I'm not sure where the bug comes from either. Replacing the `LostToNormal` call with one checking for the same conditions as the one that's supposed to call `CombatToNormal` will probably work, but that's still just a workaround after all.

**Comment by powerof3** [comment]
Ended up using the "workaround" method for now, fixing the bug itself will have to wait in a later update.
